### ISSUE TITLE
Intermittent errors on task "Register the system to Red Hat Insights"

### ISSUE THREAD

**Issue by fridim** [redhat-sap/sap-rhsm#18]
Hello,

Running the role in one of our workload, we currently have intermittent issues.
The error is:

```
TASK [redhat_sap.sap_rhsm : Register the system to Red Hat Insights] ***********
Thursday 28 January 2021  00:01:37 -0500 (0:00:04.562)       0:52:25.877 ******
fatal: [hana-ed26]: FAILED! => {"changed": true, "cmd": ["insights-client", "--register"], "delta": "0:00:4
4.065134", "end": "2021-01-28 00:02:23.080167", "msg": "non-zero return code", "rc": 1, "start": "2021-01-2
8 00:01:39.015033", "stderr": "", "stderr_lines": [], "stdout": "You successfully registered XXXXXXX to account XXXXX.\nSuccessfully registered host hana-ed26.example.com\nAutomatic s
cheduling for Insights has been enabled.\nStarting to collect Insights data for hana-ed26.example.com\nUplo
ading Insights data.\nUpload archive failed with status code  401\nUpload attempt 1 of 1 failed! Status Cod
e: 401\nAll attempts to upload have failed!\nPlease see /var/log/insights-client/insights-client.log for ad
ditional information\nUpload failed.", "stdout_lines": ["You successfully registered XXXX
 to account XXXX.", "Successfully registered host hana-ed26.example.com", "Automatic sched
uling for Insights has been enabled.", "Starting to collect Insights data for hana-ed26.example.com", "Uplo
ading Insights data.", "Upload archive failed with status code  401", "Upload attempt 1 of 1 failed! Status
 Code: 401", "All attempts to upload have failed!", "Please see /var/log/insights-client/insights-client.lo
g for additional information", "Upload failed."]}
```

## Expected

As a user of the role, i'd the task to be more resilient and retry. I'd also like to be able to set number of retries / delay with variables.

For example:

```yaml
sap_rhsm_register_insights_retries: 10
sap_rhsm_register_insights_delay: 60
```

Which would be used in the role tasks like this:

```yaml
- name: "Register the system to Red Hat Insights"
  command: "insights-client --register"
  register: r_insight_client_register
  until: r_insight_client_register is succeeded
  retries: "{{ sap_rhsm_register_insights_retries }}"
  delay: "{{ sap_rhsm_register_insights_delay }}"
  when:
  - sap_rhsm_register_insights is defined
  - sap_rhsm_register_insights
```

I haven't tested that code, it's just to illustrate.
